# -*- coding: utf-8 -*-
"""Task3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ym9pSvJOLC2L9_ngt9TRcsEmK9ix_2R4
"""

import pandas as pd

# upload file
from google.colab import files
uploaded = files.upload()

# read csv
df = pd.read_csv(list(uploaded.keys())[0])

df.head()

df.isnull().sum()

rating_columns = df.columns[2:]  # Sr no. & Student ID hata kar

avg_ratings = df[rating_columns].mean()
avg_ratings

import matplotlib.pyplot as plt

avg_ratings.sort_values().plot(kind='barh', figsize=(8,5))
plt.title("Average Rating by Course Feedback Parameters")
plt.xlabel("Average Rating")
plt.show()